import { Request, Response } from 'express';
import { RegisterMemberCommand } from '../../application/commands/RegisterMemberCommand';
import { RegisterMemberHandler } from '../../application/handlers/RegisterMemberHandler';
import { ErrorMapper } from '../dtos/ErrorContract';

/**
 * MemberController
 * Serves as the Transport Adapter. Responsible ONLY for HTTP mechanics.
 * Maps HTTP Request -> Command -> Handler -> View Model/HTTP Response.
 */
export class MemberController {
  constructor(private readonly registerMemberHandler: RegisterMemberHandler) {}

  public async register(req: Request, res: Response): Promise<void> {
    const traceContext = (req as any).traceContext; // Injected by ObservabilityMiddleware
    
    try {
      // 1. DTO Validation (Assuming handled by a prior validation middleware)
      const { email, providerToken } = req.body;

      // 2. Map to Application Command
      // The memberId is generated by the IdentityProvider port internally, 
      // but for this example, we assume it's created or provided.
      const command = new RegisterMemberCommand('APA-2026-NEW', email);

      // 3. Delegate to Application Layer
      await this.registerMemberHandler.execute(command);

      // 4. Return standard response
      res.status(201).json({
        message: 'Registration accepted.',
        // We do NOT return the full Domain Entity. We only return the specific fields dictated by the API Contract.
      });

    } catch (error: any) {
      // Map Domain/Application Errors to the strict API Error Contract
      const errorContract = ErrorMapper.mapToContract(error, traceContext.traceId);
      res.status(400).json(errorContract);
    }
  }
}
