/**
 * WorkflowParser.ts
 *
 * Converts the AST generated by YAMLParser into a strongly-typed IWorkflowModel.
 */
import { IWorkflowModel, IWorkflowTrigger, IWorkflowTransition } from '../../contracts/IWorkflowModel';

export class WorkflowParser {
  static parse(ast: Record<string, any>): IWorkflowModel {
    // 1. Extract workflow metadata
    const workflow = ast['workflow'] || {};
    const id = workflow['id'] || 'unknown';
    const version = workflow['version'] || '1.0';

    // 2. Extract trigger
    const triggerAst = ast['trigger'] || {};
    const trigger: IWorkflowTrigger = {
      event: triggerAst['event'] || 'unknown.event'
    };

    // 3. Extract states
    const states = Array.isArray(ast['states']) ? ast['states'] : [];

    // 4. Extract transitions
    const transitionsAst = Array.isArray(ast['transitions']) ? ast['transitions'] : [];
    const transitions: IWorkflowTransition[] = transitionsAst.map((t: any) => ({
      from: t.from,
      action: t.action,
      to: t.to
    }));

    // 5. Derive actions from transitions (since our DSL doesn't explicitly list actions array)
    const actionSet = new Set<string>();
    transitions.forEach(t => {
      if (t.action) actionSet.add(t.action);
    });
    const actions = Array.from(actionSet);

    return {
      id,
      version,
      trigger,
      states,
      actions,
      transitions
    };
  }
}
