import { ValidationSeverity } from "../validation/ValidationFinding";
import { TraceableArtifact } from "../contracts/TraceableArtifact";

export enum RecommendationType {
  MERGE_JOBS = "MERGE_JOBS",
  SPLIT_JOB = "SPLIT_JOB",
  PARALLELIZE_TASK = "PARALLELIZE_TASK",
  CHANGE_CAPABILITY = "CHANGE_CAPABILITY",
  REDUCE_DEPENDENCIES = "REDUCE_DEPENDENCIES"
}

/**
 * A structured, machine-readable recommendation generated by the Critic.
 * Used by the Repair Engine to modify the Execution DAG deterministically,
 * without relying on natural language understanding.
 */
export interface CriticRecommendation extends TraceableArtifact {
  readonly type: RecommendationType | string; // Allow string for forward compatibility
  
  /** Severity indicates how critical this recommendation is */
  readonly severity: ValidationSeverity;
  
  /** The target ID (Job ID or Task ID) this recommendation applies to */
  readonly targetId?: string;
  
  /** Human-readable explanation of why this recommendation was made */
  readonly description: string;
}
