// src/production/kernel/context/ProductionContext.ts

/**
 * Immutable contract that represents everything the kernel needs to plan and execute.
 * Must not contain any runtime‑specific details.
 */
export interface ProductionContext {
  /** Unique identifier for the request */
  readonly contextId: string;
  /** User supplied request (raw text, JSON, etc.) */
  readonly userRequest: unknown;
  /** Blueprint generated by the Intelligence layer */
  readonly blueprint: unknown;
  /** Target platform or output format */
  readonly generationTarget: unknown;
  /** Runtime options supplied by the caller */
  readonly runtimeOptions?: unknown;
  /** Optional metadata (e.g., trace IDs, correlation IDs) */
  readonly metadata?: Record<string, unknown>;
}
