import { ContextRanking } from "../contracts/ContextRanking";
import { RetrievalStrategy } from "../contracts/RetrievalStrategy";
import { CandidateResult } from "./CandidateGenerator";
import { MemoryPolicy } from "../contracts/MemoryPolicy";

export interface RankedCandidate extends CandidateResult {
  ranking: ContextRanking;
}

export class RankingEngine {
  rank(candidates: CandidateResult[], strategy: RetrievalStrategy, policy: MemoryPolicy): RankedCandidate[] {
    const ranked: RankedCandidate[] = candidates.map(candidate => {
      let score = 0.5;
      let reason = "Context matches selection criteria.";
      const confidence = 1.0; // Deterministic strategies have confidence 1.0

      switch (strategy) {
        case RetrievalStrategy.LINEAGE:
          // Closer depth = higher score
          const depth = Math.floor(candidate.knowledgePath.length / 2); // path contains edge + node pairs
          score = Math.max(1.0 - (depth * 0.1), 0.1); 
          reason = `Directly derived in lineage (depth: ${depth})`;
          break;
        case RetrievalStrategy.CAPABILITY:
          score = 0.9;
          reason = `Generated by requested capability: ${candidate.node.metadata?.creatorCapability}`;
          break;
        case RetrievalStrategy.WORKFLOW:
          score = 0.8;
          reason = `Belongs to requested workflow: ${candidate.node.metadata?.traceId}`;
          break;
        case RetrievalStrategy.HYBRID:
          score = 0.95;
          reason = `Matches multiple structural bounds`;
          break;
      }

      return {
        ...candidate,
        ranking: { score, reason, confidence }
      };
    });

    // Filter by MemoryPolicy.minimumScore and sort descending by score
    return ranked
      .filter(c => c.ranking.score >= policy.minimumScore)
      .sort((a, b) => b.ranking.score - a.ranking.score);
  }
}
