// services/applicationBlueprintService.js – Combine all blueprints into a single Application Blueprint

/**
 * Generate an Application Blueprint from the various lower‑level blueprints.
 *
 * @param {Object} spec - Research Specification (output of the AI analysis).
 * @param {Object} project - Project Blueprint (generated by toolBlueprintService).
 * @param {Object} dbBlueprint - Database Blueprint (generated by databaseBlueprintService).
 * @param {Object} uiBlueprint - UI Blueprint (generated by uiBlueprintService).
 * @returns {Object} Application Blueprint JSON with a canonical structure for downstream generators.
 */
function generateApplicationBlueprint(spec, project, dbBlueprint, uiBlueprint) {
  // ----- Validation -----
  if (!spec || typeof spec !== 'object') throw new Error('Invalid Research Specification');
  if (!project || typeof project !== 'object') throw new Error('Invalid Project Blueprint');
  if (!dbBlueprint || typeof dbBlueprint !== 'object') throw new Error('Invalid Database Blueprint');
  if (!uiBlueprint || typeof uiBlueprint !== 'object') throw new Error('Invalid UI Blueprint');

  // ----- 1️⃣ Application name & description -----
  const appName = spec.researchTitle
    ? `${spec.researchTitle.replace(/\s+/g, '')}App`
    : 'ResearchToolApp';

  const appDescription = spec.researchObjectives && spec.researchObjectives.length > 0
    ? spec.researchObjectives.join(' ')
    : spec.methodology || 'A research‑driven application generated by UltimateAI.';

  // ----- 2️⃣ Merge pages & navigation -----
  // Prefer UI blueprint pages; fall back to project pages if UI omitted.
  const pages = uiBlueprint.pages && uiBlueprint.pages.length > 0 ? uiBlueprint.pages : (project.pages || []);
  const navigation = uiBlueprint.navigation && uiBlueprint.navigation.length > 0 ? uiBlueprint.navigation : [];

  // ----- 3️⃣ Forms -----
  const forms = uiBlueprint.forms && uiBlueprint.forms.length > 0 ? uiBlueprint.forms : (project.forms || []);

  // ----- 4️⃣ Database -----
  const database = {
    tables: dbBlueprint.tables || {},
    relationships: dbBlueprint.relationships || [],
    indexes: dbBlueprint.indexes || [],
    supabaseCompatible: !!dbBlueprint.supabaseCompatible,
  };

  // ----- 5️⃣ Reports -----
  const reports = uiBlueprint.reports && uiBlueprint.reports.length > 0 ? uiBlueprint.reports : (project.reports || []);

  // ----- 6️⃣ Deployment -----
  const deployment = project.deploymentTargets && project.deploymentTargets.length > 0
    ? project.deploymentTargets
    : [];

  // ----- Assemble final blueprint -----
  const application = {
    name: appName,
    description: appDescription,
  };

  return {
    application,
    pages,
    navigation,
    forms,
    database,
    reports,
    deployment,
  };
}

module.exports = {
  generateApplicationBlueprint,
};
