// services/databaseBlueprintService.js – Transform Research Specification & Project Blueprint into a Database Blueprint

/**
 * Generate a Database Blueprint from a Research Specification and a Project Blueprint.
 * The output is a structured JSON object describing tables, columns, data types,
 * relationships, index recommendations and Supabase compatibility.
 *
 * @param {Object} spec - Research Specification (output of the analysis step).
 * @param {Object} project - Project Blueprint generated by toolBlueprintService.
 * @returns {Object} Database Blueprint.
 */
function generateDatabaseBlueprint(spec, project) {
  if (!spec || typeof spec !== 'object') {
    throw new Error('Invalid Research Specification');
  }
  if (!project || typeof project !== 'object') {
    throw new Error('Invalid Project Blueprint');
  }

  // Helper: map UI parameter type to a generic SQL data type (Supabase compatible)
  const typeMap = {
    text: 'text',
    textarea: 'text',
    number: 'numeric',
    date: 'date',
    dropdown: 'text',
    gps: 'text',
    photo: 'text',
    video: 'text',
    audio: 'text',
    pdf: 'text',
    checkbox: 'boolean',
    radio: 'text',
    email: 'text',
    phone: 'text',
    url: 'text',
    // fallback
    default: 'text',
  };
  const mapParamToColumn = p => {
    const dbType = typeMap[p.type] || typeMap.default;
    return { name: p.name || 'unnamed', type: dbType, required: !!p.required };
  };

  // ---------------------------------------------------------------------
  // 1️⃣ Tables and Columns
  // ---------------------------------------------------------------------
  const tables = {};
  const baseTables = Array.isArray(project.databaseTables) ? project.databaseTables : [];
  // Ensure each listed table exists in the blueprint
  baseTables.forEach(tbl => {
    tables[tbl] = [];
    // Primary key for every table
    tables[tbl].push({ name: 'id', type: 'uuid', required: true, primaryKey: true });
  });

  // Assign parameters to tables – simple heuristic:
  //   * If a table name appears as a prefix in the parameter name, use that table.
  //   * Otherwise, assign to the first table (or create an "observations" fallback).
  const defaultTable = tables['observations'] ? 'observations' : baseTables[0] || 'observations';
  if (!tables[defaultTable]) tables[defaultTable] = [{ name: 'id', type: 'uuid', required: true, primaryKey: true }];

  (spec.recommendedParameters || []).forEach(p => {
    const name = p.name || '';
    // Find a table whose name is a substring of the parameter name (case‑insensitive)
    const matchingTable = baseTables.find(t => name.toLowerCase().includes(t.toLowerCase())) || defaultTable;
    // Avoid duplicate column names
    const exists = tables[matchingTable].some(col => col.name === name);
    if (!exists) {
      tables[matchingTable].push(mapParamToColumn(p));
    }
  });

  // ---------------------------------------------------------------------
  // 2️⃣ Relationships (foreign keys)
  // ---------------------------------------------------------------------
  const relationships = [];
  // If we have a "projects" table, link each other table to it via project_id (if not already present)
  if (tables['projects']) {
    Object.keys(tables).forEach(tbl => {
      if (tbl === 'projects') return;
      // Ensure foreign key column exists
      const fkName = 'project_id';
      const hasFk = tables[tbl].some(col => col.name === fkName);
      if (!hasFk) {
        tables[tbl].push({ name: fkName, type: 'uuid', required: false });
      }
      relationships.push({
        fromTable: tbl,
        fromColumn: fkName,
        toTable: 'projects',
        toColumn: 'id',
      });
    });
  }

  // ---------------------------------------------------------------------
  // 3️⃣ Index Recommendations
  // ---------------------------------------------------------------------
  const indexes = [];
  // Primary key index is implicit, add indexes for foreign keys
  relationships.forEach(rel => {
    indexes.push({ table: rel.fromTable, column: rel.fromColumn, type: 'btree' });
  });

  // ---------------------------------------------------------------------
  // 4️⃣ Supabase Compatibility Flag
  // ---------------------------------------------------------------------
  const supabaseCompatible = true; // Our schema follows Supabase conventions (uuid PK, etc.)

  return {
    tables,
    relationships,
    indexes,
    supabaseCompatible,
  };
}

module.exports = {
  generateDatabaseBlueprint,
};
