// services/githubService.js
// Creates a GitHub repository and pushes generated source files via GitHub API.

const GITHUB_TOKEN    = process.env.GITHUB_TOKEN;
const GITHUB_USERNAME = process.env.GITHUB_USERNAME;
const GITHUB_API      = 'https://api.github.com';

function ghHeaders() {
  return {
    'Authorization': `Bearer ${GITHUB_TOKEN}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

/**
 * Sanitise an app name into a valid repo slug.
 */
function toSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').substring(0, 80);
}

/**
 * Create a public GitHub repository.
 * @returns {Object} { repoName, repoUrl, cloneUrl }
 */
async function createRepo(appName) {
  if (!GITHUB_TOKEN || !GITHUB_USERNAME) {
    throw new Error('GITHUB_TOKEN and GITHUB_USERNAME must be set in .env');
  }

  const repoName = `${toSlug(appName)}-${Date.now().toString(36)}`;

  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: 'POST',
    headers: ghHeaders(),
    body: JSON.stringify({
      name: repoName,
      description: `Generated by UltimateAI — ${appName}`,
      private: false,
      auto_init: true,  // Creates default branch with README
    }),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(`GitHub createRepo failed: ${err.message}`);
  }

  const data = await res.json();
  return {
    repoName: data.name,
    repoUrl: data.html_url,
    cloneUrl: data.clone_url,
    defaultBranch: data.default_branch || 'main',
  };
}

/**
 * Push a single file to a GitHub repo via Contents API.
 */
async function pushFile(repoName, filePath, content) {
  // Get SHA of existing file (needed for update, undefined for new)
  let sha;
  const getRes = await fetch(
    `${GITHUB_API}/repos/${GITHUB_USERNAME}/${repoName}/contents/${filePath}`,
    { headers: ghHeaders() }
  );
  if (getRes.ok) {
    const existing = await getRes.json();
    sha = existing.sha;
  }

  const body = {
    message: `feat: add ${filePath}`,
    content: Buffer.from(content).toString('base64'),
    branch: 'main',
  };
  if (sha) body.sha = sha;

  const putRes = await fetch(
    `${GITHUB_API}/repos/${GITHUB_USERNAME}/${repoName}/contents/${filePath}`,
    { method: 'PUT', headers: ghHeaders(), body: JSON.stringify(body) }
  );

  if (!putRes.ok) {
    const err = await putRes.json();
    throw new Error(`GitHub pushFile (${filePath}) failed: ${err.message}`);
  }
}

/**
 * Push all generated project files to a GitHub repo.
 * @param {string} repoName  - Repo slug (already created)
 * @param {Object} files     - { 'path/file.ext': 'file content string', ... }
 */
async function pushFiles(repoName, files) {
  for (const [filePath, content] of Object.entries(files)) {
    await pushFile(repoName, filePath, content);
  }
}

module.exports = { createRepo, pushFiles, toSlug };
