// src/pages/GeneratedApps.jsx
import React, { useEffect, useState } from 'react';
import { get } from '../services/apiClient';
import { useNavigate } from 'react-router-dom';
import {
  Monitor, FileText, Settings, LayoutTemplate, MessageSquare,
  Download, Eye, Rocket, CheckCircle2, AlertCircle, Loader2,
  Moon, Sun, FolderOpen
} from 'lucide-react';
import logoUrl from '../../logo-ultimateAI.png';

function GeneratedApps() {
  const [apps, setApps] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedApp, setSelectedApp] = useState(null);
  const [isDarkMode, setIsDarkMode] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    document.documentElement.classList.add('dark');
  }, []);

  useEffect(() => {
    const fetchApps = async () => {
      try {
        const data = await get('/api/generated-apps');
        setApps(data);
      } catch (e) {
        console.error(e);
        setError('Failed to load generated applications.');
      } finally {
        setLoading(false);
      }
    };
    fetchApps();
  }, []);

  const viewBlueprint = (app) => setSelectedApp(app);

  const downloadProject = (app) => {
    const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:3001';
    const url = `${API_BASE}/api/download/${app.projectId}`;
    const link = document.createElement('a');
    link.href = url;
    link.download = `${(app.applicationBlueprint?.application?.name || 'research-app').toLowerCase().replace(/\s+/g, '-')}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="min-h-screen bg-[#0a0f1c] text-slate-200">
      {/* HEADER */}
      <header className="border-b border-white/5 bg-[#0a0f1c]">
        <div className="max-w-[1400px] mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <img src={logoUrl} alt="UltimateAI Logo" className="h-10 w-auto object-contain" />
            <div className="hidden md:block">
              <h1 className="font-bold text-2xl text-white tracking-tight leading-none">
                Ultimate<span className="text-blue-500">AI</span>
              </h1>
              <span className="text-[9px] font-semibold text-slate-400 uppercase tracking-[0.2em]">
                Helping Researchers Build, Not Code.
              </span>
            </div>
          </div>

          <nav className="hidden lg:flex items-center gap-8">
            <button onClick={() => navigate('/research-builder')} className="flex items-center gap-2 text-slate-400 hover:text-slate-200 transition-colors font-medium text-sm">
              <MessageSquare className="w-4 h-4" /> Research Builder
            </button>
            <button onClick={() => navigate('/my-projects')} className="flex items-center gap-2 text-slate-400 hover:text-slate-200 transition-colors font-medium text-sm">
              <FileText className="w-4 h-4" /> My Projects
            </button>
            <button className="flex items-center gap-2 text-blue-400 border-b-2 border-blue-500 pb-[26px] pt-[28px] font-medium text-sm">
              <Monitor className="w-4 h-4" /> Generated Apps
            </button>
            <button className="flex items-center gap-2 text-slate-400 hover:text-slate-200 transition-colors font-medium text-sm">
              <LayoutTemplate className="w-4 h-4" /> Templates
            </button>
            <button className="flex items-center gap-2 text-slate-400 hover:text-slate-200 transition-colors font-medium text-sm">
              <Settings className="w-4 h-4" /> Settings
            </button>
          </nav>

          <div className="flex items-center gap-4">
            <button
              onClick={() => setIsDarkMode(!isDarkMode)}
              className="p-2.5 rounded-full bg-slate-800/50 hover:bg-slate-700/50 border border-white/5 transition-colors text-slate-300"
            >
              {isDarkMode ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>
            <div className="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-white font-semibold cursor-pointer">U</div>
          </div>
        </div>
      </header>

      {/* MAIN */}
      <main className="max-w-[1200px] mx-auto px-6 py-8 space-y-6 pb-32">
        {/* Page Title */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-white">Generated Applications</h2>
            <p className="text-slate-400 text-sm mt-1">Research tools generated by UltimateAI</p>
          </div>
          <button
            onClick={() => navigate('/research-builder')}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-xl font-medium transition-all shadow-lg shadow-blue-900/30 text-sm"
          >
            <Rocket className="w-4 h-4" /> New Research
          </button>
        </div>

        {/* Loading */}
        {loading && (
          <div className="flex flex-col items-center justify-center py-24 gap-4">
            <Loader2 className="w-8 h-8 animate-spin text-blue-400" />
            <p className="text-slate-400">Loading applications...</p>
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="flex items-center gap-3 p-4 text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl">
            <AlertCircle className="w-5 h-5 shrink-0" />
            <p className="text-sm">{error}</p>
          </div>
        )}

        {/* Empty */}
        {!loading && !error && apps.length === 0 && (
          <div className="flex flex-col items-center justify-center py-24 gap-4 bg-[#111827] border border-white/5 rounded-2xl">
            <FolderOpen className="w-12 h-12 text-slate-600" />
            <p className="text-slate-400 font-medium">No generated applications yet.</p>
            <button
              onClick={() => navigate('/research-builder')}
              className="mt-2 flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-xl font-medium transition-all text-sm"
            >
              <Rocket className="w-4 h-4" /> Generate Your First App
            </button>
          </div>
        )}

        {/* Apps Grid */}
        {!loading && !error && apps.length > 0 && (
          <div className="grid gap-4">
            {apps.map((app) => {
              const appName = app.applicationBlueprint?.application?.name || app.spec?.researchTitle || 'Unnamed Application';
              const appDesc = app.applicationBlueprint?.application?.description || app.spec?.researchType || 'Research Tool';
              const pages = app.applicationBlueprint?.pages || [];
              const tables = app.applicationBlueprint?.database?.tables || [];
              return (
                <div key={app.projectId} className="bg-[#111827] border border-white/5 rounded-2xl p-6 hover:border-blue-900/40 transition-all shadow-xl">
                  <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                    <div className="flex items-start gap-4">
                      <div className="w-12 h-12 rounded-xl bg-blue-600/20 border border-blue-500/30 flex items-center justify-center shrink-0">
                        <Rocket className="w-6 h-6 text-blue-400" />
                      </div>
                      <div>
                        <h3 className="text-lg font-bold text-white">{appName}</h3>
                        <p className="text-sm text-slate-400 mt-1">{appDesc}</p>
                        <div className="flex items-center gap-2 mt-3">
                          <span className="inline-flex items-center gap-1 text-xs bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2.5 py-1 rounded-full font-medium">
                            <CheckCircle2 className="w-3 h-3" /> Generated
                          </span>
                          {pages.length > 0 && (
                            <span className="text-xs bg-slate-800 text-slate-400 border border-slate-700 px-2.5 py-1 rounded-full">
                              {pages.length} Pages
                            </span>
                          )}
                          {tables.length > 0 && (
                            <span className="text-xs bg-slate-800 text-slate-400 border border-slate-700 px-2.5 py-1 rounded-full">
                              {tables.length} Tables
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-slate-600 mt-2 font-mono">ID: {app.projectId}</p>
                      </div>
                    </div>

                    <div className="flex gap-3 shrink-0">
                      <button
                        onClick={() => viewBlueprint(app)}
                        className="flex items-center gap-2 bg-[#182133] hover:bg-slate-700 text-slate-200 border border-slate-700 px-4 py-2 rounded-lg text-sm font-medium transition-all"
                      >
                        <Eye className="w-4 h-4" /> View Blueprint
                      </button>
                      <button
                        onClick={() => downloadProject(app)}
                        className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-all shadow-lg shadow-emerald-900/20"
                      >
                        <Download className="w-4 h-4" /> Download
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Blueprint Modal */}
        {selectedApp && (
          <div
            className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setSelectedApp(null)}
          >
            <div
              className="bg-[#111827] border border-white/10 rounded-2xl p-8 max-w-2xl w-full max-h-[80vh] overflow-y-auto shadow-2xl"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-bold text-white">Application Blueprint</h3>
                <button onClick={() => setSelectedApp(null)} className="text-slate-400 hover:text-white text-2xl leading-none">&times;</button>
              </div>
              <pre className="text-xs text-slate-300 bg-[#0f1523] border border-slate-800 rounded-xl p-4 overflow-auto max-h-[55vh] font-mono whitespace-pre-wrap">
                {JSON.stringify(selectedApp.applicationBlueprint || selectedApp, null, 2)}
              </pre>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export default GeneratedApps;
