/**
 * IExecutionEvent.ts
 *
 * Internal events generated by the Execution Kernel.
 * Will be consumed by Observability later.
 */

export type ExecutionEventType = 
  | 'ExecutionStarted'
  | 'StateTransitioned'
  | 'ExecutionCompleted'
  | 'ExecutionFailed'
  | 'ExecutionPaused'
  | 'ExecutionResumed'
  | 'ExecutionRetried'
  | 'ExecutionTimedOut'
  | 'ExecutionRejected'
  | 'ExecutionQueued'
  | 'ExecutionMovedToDLQ'
  | 'JobQueued'
  | 'JobDequeued'
  | 'JobCompleted'
  | 'JobFailed'
  | 'WorkerStarted'
  | 'WorkerStopped'
  | 'QueueCreated'
  | 'QueueOverflow'
  | 'PackageLoaded';

export interface IExecutionEvent {
  readonly event_id: string;
  readonly event_version: string;
  readonly type: ExecutionEventType;
  readonly execution_id: string;
  readonly timestamp: string;
  readonly payload: any;
}
