/**
 * IRuntimeDecision.ts
 *
 * Defines the strict outcomes generated by Evaluative Managers and orchestrator.
 */

export type RuntimeDecisionType = 'START' | 'RETRY' | 'WAIT' | 'REJECT' | 'DLQ' | 'CONTINUE';

export interface IRuntimeDecision {
  readonly decision: RuntimeDecisionType;
  readonly reason: string;
  readonly wait_ms?: number;
}
