// src/production/learning/validation/ValidationReport.ts

import { RuleResult } from "./RuleResult";

/**
 * The final output of the LearningValidator.
 * Immutable record of the validation process.
 */
export interface ValidationReport {
  readonly candidateId: string;
  readonly startedAt: number;
  readonly finishedAt: number;
  readonly durationMs: number;
  
  readonly ruleResults: readonly RuleResult[];
  
  /**
   * Final decision: True if all rules passed, or if failures were only INFO/WARNING level.
   * False if ANY rule returned passed=false AND severity=ERROR.
   */
  readonly passed: boolean;
  
  /** High-level summary generated by the orchestrator based on rule results */
  readonly summary: string;
}
