// src/production/providers/contracts/ProviderResponse.ts

/**
 * A vendor-agnostic response returning from the AI Provider back to UltimateAI.
 */
export interface ProviderResponse {
  /** High-level status of the response */
  readonly status: "success" | "partial" | "error";

  /** The primary outputs generated by the AI (e.g., text strings, structured data) */
  readonly outputs: readonly unknown[];

  /** Any artifacts produced during generation (e.g., image files, code blobs) */
  readonly artifacts?: readonly unknown[];

  /** Usage metrics such as tokens consumed, latency, etc. */
  readonly usage?: Record<string, unknown>;

  /** Non-critical warnings from the provider */
  readonly warnings?: readonly string[];

  /** Errors encountered during execution, if any */
  readonly errors?: readonly unknown[];

  /** Arbitrary metadata associated with this response */
  readonly metadata?: Record<string, unknown>;
}
