import React, { useState, useEffect, useCallback } from 'react';
import './simulator.css';
import LeftSidebarHUD from './components/LeftSidebarHUD.jsx';
import CenterHologramHUD from './components/CenterHologramHUD.jsx';
import MobileSimulatorHUD from './components/MobileSimulatorHUD.jsx';
import UniverseCosmosBackground from './components/UniverseCosmosBackground.jsx';

// Interactive Modals
import AnalyzeDataModal from './modals/AnalyzeDataModal.jsx';
import MemoryVaultExplorer from './modals/MemoryVaultExplorer.jsx';
import ActivityFeedDrawer from './modals/ActivityFeedDrawer.jsx';
import ControlCenterModal from './modals/ControlCenterModal.jsx';
import LiveCertificationDashboardModal from './modals/LiveCertificationDashboardModal.jsx';
import ConnectionsModal from './modals/ConnectionsModal.jsx';

import { useJinAvatar } from '../../hooks/useJinAvatar.js';
import { useVoiceEngine } from '../../hooks/useVoiceEngine.js';
import { useAudioAnalyzer } from '../../hooks/useAudioAnalyzer.js';
import { simulatorOrchestratorInstance } from '../../services/orchestrator/SimulatorOrchestrator.js';
import { conversationEngineInstance } from '../../services/conversation/ConversationEngine.js';

export default function ChatSimulator() {
  const [activeTab, setActiveTab] = useState('talk_to_jin');
  const [messages, setMessages] = useState([]);
  const [latestResponse, setLatestResponse] = useState('');
  const [simulatorMode, setSimulatorMode] = useState('CONVERSATION'); // 'CONVERSATION' | 'SEARCH' | 'INSIGHTS' | 'APP_PREVIEW'
  const [generatedAppCode, setGeneratedAppCode] = useState(null);
  const [liveSearchSources, setLiveSearchSources] = useState([]);

  // Modal Open States
  const [isAnalyzeModalOpen, setIsAnalyzeModalOpen] = useState(false);
  const [isMemoryModalOpen, setIsMemoryModalOpen] = useState(false);
  const [isActivityDrawerOpen, setIsActivityDrawerOpen] = useState(false);
  const [isControlModalOpen, setIsControlModalOpen] = useState(false);
  const [isCertModalOpen, setIsCertModalOpen] = useState(false);
  const [isConnectionsModalOpen, setIsConnectionsModalOpen] = useState(false);

  // JIN Avatar FSM Hook (Single Source of Truth)
  const { state: avatarState, isListening, isProcessing, isSpeaking } = useJinAvatar();

  // Audio-Reactive metrics Hook
  const audioMetrics = useAudioAnalyzer(avatarState);

  // Sync messages from conversation engine
  const refreshMessages = () => {
    setMessages(conversationEngineInstance.getHistory());
  };

  useEffect(() => {
    refreshMessages();
  }, []);

  // Voice Interaction Hook with instant Barge-in
  const handleBargeIn = useCallback(() => {
    console.log('[CHAT] User barge-in detected! Stopping JIN speech.');
  }, []);

  const { startListening, stopListening } = useVoiceEngine({
    onBargeIn: handleBargeIn
  });

  // Handle Text/Voice Prompts through SimulatorOrchestrator
  const handleExecutePrompt = async (promptText, options = {}) => {
    try {
      // Auto-detect intent and switch simulator display mode
      const lower = (promptText || '').toLowerCase();
      if (lower.includes('cari') || lower.includes('search') || lower.includes('global')) {
        setSimulatorMode('SEARCH');
      } else if (lower.includes('buat') || lower.includes('aplikasi') || lower.includes('app') || lower.includes('build')) {
        setSimulatorMode('APP_PREVIEW');
      } else if (lower.includes('analisis') || lower.includes('risiko') || lower.includes('insight') || options.attachedImage) {
        setSimulatorMode('CONVERSATION');
      } else {
        setSimulatorMode('CONVERSATION');
      }

      refreshMessages();
      await simulatorOrchestratorInstance.executeUserPrompt(promptText, {
        attachedImage: options.attachedImage || null,
        onStreamChunk: (_, fullText) => {
          setLatestResponse(fullText);
          refreshMessages();
        },
        onResponseReady: (response) => {
          setLatestResponse(response);
          refreshMessages();
          // Extract HTML / UI code block if generated by JIN
          const htmlMatch = response.match(/```html\s*([\s\S]*?)\s*```/i) || response.match(/```(?:xml|ui)\s*([\s\S]*?)\s*```/i);
          if (htmlMatch && htmlMatch[1]) {
            setGeneratedAppCode(htmlMatch[1]);
            setSimulatorMode('APP_PREVIEW');
          }
        }
      });
      refreshMessages();
    } catch (err) {
      console.error('Failed to execute prompt:', err);
    }
  };

  const [liveTranscript, setLiveTranscript] = useState('');

  // Toggle Mic on/off for Natural Conversation
  const handleMicToggle = () => {
    if (isListening) {
      simulatorOrchestratorInstance.stopVoiceInput();
      setLiveTranscript('');
    } else {
      simulatorOrchestratorInstance.startVoiceInput({
        onTranscript: (text) => {
          setLiveTranscript(text);
        },
        onFinalTranscript: (text) => {
          setLiveTranscript(text);
          handleExecutePrompt(text);
          setTimeout(() => setLiveTranscript(''), 3500);
        }
      });
    }
  };

  // Sidebar Menu Action Handlers
  const handleSidebarAction = (action) => {
    if (action === 'talk') {
      handleMicToggle();
    } else if (action === 'chat') {
      setSimulatorMode('CONVERSATION');
    } else if (action === 'search') {
      setSimulatorMode('SEARCH');
    } else if (action === 'analyze') {
      setIsAnalyzeModalOpen(true);
    } else if (action === 'deep_analysis') {
      setSimulatorMode('INSIGHTS');
    } else if (action === 'generate') {
      setSimulatorMode('APP_PREVIEW');
    } else if (action === 'vault') {
      setIsMemoryModalOpen(true);
    } else if (action === 'feed') {
      setIsActivityDrawerOpen(true);
    } else if (action === 'system' || action === 'control') {
      setIsControlModalOpen(true);
    } else if (action === 'connections') {
      setIsConnectionsModalOpen(true);
    }
  };

  const handleSelectApp = (app) => {
    if (!app) return;
    if (app.id === 'DOCUMENT_STUDIO') {
      setIsAnalyzeModalOpen(true);
    } else if (app.id === 'DATA_LAB') {
      setSimulatorMode('INSIGHTS');
    } else if (app.id === 'CODE_LAB') {
      setSimulatorMode('APP_PREVIEW');
    } else if (app.id === 'MEDIA_STUDIO') {
      setSimulatorMode('MEDIA');
    } else if (app.id === 'KNOWLEDGE_LAB') {
      setSimulatorMode('SEARCH');
    } else if (app.id === 'IMAGE_STUDIO') {
      setSimulatorMode('MEDIA');
    }
    if (app.actionPrompt) {
      handleExecutePrompt(app.actionPrompt);
    }
  };

  return (
    <div className="w-screen h-screen bg-[#040711] text-slate-100 flex overflow-hidden font-sans relative">
      {/* Dynamic Deep Universe, Galaxy, Planets, Stars & Meteors Cosmos Background */}
      <UniverseCosmosBackground />

      {/* 1. Left Sidebar Navigation HUD */}
      <div className="z-10 h-full">
        <LeftSidebarHUD
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          onActionClick={handleSidebarAction}
        />
      </div>

      {/* 2. Center 6-App Cyber Studio HUD & Voice Command Console */}
      <main className="flex-1 h-full flex flex-col justify-between py-1 overflow-hidden relative z-10">
        <CenterHologramHUD
          avatarState={avatarState}
          audioMetrics={audioMetrics}
          onSettingsClick={() => setIsControlModalOpen(true)}
          onNotificationClick={() => setIsActivityDrawerOpen(true)}
          onOpenCertDashboard={() => setIsCertModalOpen(true)}
          onSelectApp={handleSelectApp}
          isListening={isListening}
          onMicClick={handleMicToggle}
          onSubmitText={handleExecutePrompt}
          liveTranscript={liveTranscript}
        />
      </main>

      {/* 3. Right Mobile Simulator Frame (Live Intelligence Display) */}
      <MobileSimulatorHUD
        avatarState={avatarState}
        audioMetrics={audioMetrics}
        messages={messages}
        latestResponse={latestResponse}
        isProcessing={isProcessing}
        activeMode={simulatorMode}
        onModeChange={setSimulatorMode}
        generatedAppCode={generatedAppCode}
        liveSearchSources={liveSearchSources}
        onAnalyzeDocument={(doc) => {
          setSimulatorMode('INSIGHTS');
          const docText = doc.content || doc.preview || '';
          handleExecutePrompt(
            `Berikut adalah isi lengkap dari dokumen "${doc.fileName}" (${doc.type}) yang baru saya unggah:\n\n` +
            `=== ISI DOKUMEN (HALAMAN 1 S/D AKHIR) ===\n` +
            `${docText}\n` +
            `=== AKHIR DOKUMEN ===\n\n` +
            `Tolong analisis isi dokumen di atas secara mendalam dan berikan:\n` +
            `1. Ringkasan Eksekutif & Topik Utama\n` +
            `2. Poin-Poin Temuan Kunci & Metodologi/Pembahasan\n` +
            `3. Kesimpulan Akhir dan Rekomendasi/Tindak Lanjut.`
          );
        }}
      />

      {/* Interactive Modals */}
      <AnalyzeDataModal
        isOpen={isAnalyzeModalOpen}
        onClose={() => setIsAnalyzeModalOpen(false)}
        onAnalyzeDocument={(doc) => {
          setSimulatorMode('INSIGHTS');
          const docText = doc.content || doc.preview || '';
          handleExecutePrompt(
            `Berikut adalah isi lengkap dari dokumen "${doc.fileName}" (${doc.type}) yang baru saya unggah:\n\n` +
            `=== ISI DOKUMEN (HALAMAN 1 S/D AKHIR) ===\n` +
            `${docText}\n` +
            `=== AKHIR DOKUMEN ===\n\n` +
            `Tolong analisis isi dokumen di atas secara mendalam dan berikan:\n` +
            `1. Ringkasan Eksekutif & Topik Utama\n` +
            `2. Poin-Poin Temuan Kunci & Metodologi/Pembahasan\n` +
            `3. Kesimpulan Akhir dan Rekomendasi/Tindak Lanjut.`
          );
        }}
      />

      <MemoryVaultExplorer
        isOpen={isMemoryModalOpen}
        onClose={() => setIsMemoryModalOpen(false)}
      />

      <ActivityFeedDrawer
        isOpen={isActivityDrawerOpen}
        onClose={() => setIsActivityDrawerOpen(false)}
      />

      <ControlCenterModal
        isOpen={isControlModalOpen}
        onClose={() => setIsControlModalOpen(false)}
      />

      <LiveCertificationDashboardModal
        isOpen={isCertModalOpen}
        onClose={() => setIsCertModalOpen(false)}
      />

      <ConnectionsModal
        isOpen={isConnectionsModalOpen}
        onClose={() => setIsConnectionsModalOpen(false)}
      />
    </div>
  );
}
