// src/production/reasoning/contracts/ReasoningResult.ts

import { IRuntimeResult } from "../../runtime/contracts/IRuntimeResult";
import { ReasoningConclusion } from "./ReasoningConclusion";
import { LearnedKnowledge } from "../../learning/promotion/LearnedKnowledge";
import { KnowledgeGraphRelation } from "../../evolution/KnowledgeGraphRelation";
import { IArtifact, ArtifactIdentity, ArtifactTrace } from "../../runtime/contracts/IArtifact";

export interface ReasoningResultPayload extends IArtifact {
  readonly identity: ArtifactIdentity;
  readonly trace: ArtifactTrace;

  readonly conclusion: ReasoningConclusion;
  
  /** The actual knowledge objects utilized */
  readonly usedKnowledge: readonly LearnedKnowledge[];
  
  /** The relational edges utilized */
  readonly usedRelations: readonly KnowledgeGraphRelation[];
  
  /** Additional warnings generated by the Validator */
  readonly validatorWarnings: readonly string[];
}

/**
 * The final output returned to the Coordinator, wrapped in the standard Runtime Result.
 */
export type ReasoningResult = IRuntimeResult<ReasoningResultPayload>;
