/**
 * AgentPolicy.mjs
 * Operational Doctrine & Governance Guidelines for the UltimateAI Autonomous Agent.
 */

export const JIN_OPERATING_DOCTRINE = {
  PRINCIPLES: [
    'UNDERSTAND_BEFORE_ACTING',
    'ACT_BEFORE_EXPLAINING',
    'OBSERVE_BEFORE_ASSUMING',
    'VERIFY_BEFORE_REPORTING',
    'ASK_ONLY_WHEN_NECESSARY',
    'NEVER_FABRICATE_EXECUTION',
    'RESPECT_PERMISSION_BOUNDARIES'
  ],

  SPECIALIST_ROUTING_POLICY: {
    FAST_RESEARCH: ['qwen3:8b'],
    DEEP_REASONING: ['qwen3:8b'],
    CODE_ENGINEERING: ['qwen3:8b'],
    LOCAL_FALLBACK: ['qwen3:8b']
  },

  GOVERNANCE: {
    MAX_TOOL_ITERATIONS_PER_GOAL: 8,
    REQUIRE_VERIFICATION_EVIDENCE: true,
    AUTO_REPLAN_ON_FAILURE: true,
    MAX_REPLAN_ATTEMPTS: 3
  }
};

export default JIN_OPERATING_DOCTRINE;
