import { ValidationFinding } from "./ValidationFinding";
import { TraceableArtifact } from "../contracts/TraceableArtifact";

/**
 * Comprehensive report generated by the ExecutionValidator.
 */
export interface ValidationReport extends TraceableArtifact {
  /** True if there are NO findings with ERROR severity */
  readonly isValid: boolean;
  
  /** All findings (errors, warnings, info) aggregated from all rules */
  readonly findings: readonly ValidationFinding[];
  
  /** High-level statistics of the execution plan */
  readonly statistics: {
    readonly totalJobs: number;
    readonly totalTasks: number;
    readonly ruleExecutionCount: number;
  };
  
  /** Duration of the validation process in milliseconds */
  readonly durationMs: number;
}
