// src/production/learning/pattern/PatternEvidence.ts

/**
 * Represents the justification for why a pattern was identified.
 * Traces back to specific experiences and raw facts.
 */
export interface PatternEvidence {
  /** The ID of the underlying Experience that supports or contradicts this pattern */
  readonly experienceId: string;
  
  /** The importance/relevance of this specific experience to the pattern (e.g., 0.0 to 1.0) */
  readonly weight: number;
  
  /** A semantic explanation generated by the AI describing why this forms evidence */
  readonly rationale: string;
}
