/**
 * JinAvatarStates.js
 * Definitions of Avatar States and Transition Events.
 */

export const AVATAR_STATES = {
  IDLE: 'IDLE',
  LISTENING: 'LISTENING',
  PROCESSING: 'PROCESSING',
  SPEAKING: 'SPEAKING',
  INTERRUPTED: 'INTERRUPTED',
  ERROR: 'ERROR'
};

export const AVATAR_EVENTS = {
  MIC_ACTIVATED: 'MIC_ACTIVATED',
  INPUT_COMPLETED: 'INPUT_COMPLETED',
  REQUEST_STARTED: 'REQUEST_STARTED',
  RESPONSE_READY: 'RESPONSE_READY',
  RESPONSE_TEXT_ONLY: 'RESPONSE_TEXT_ONLY',
  SPEECH_FINISHED: 'SPEECH_FINISHED',
  USER_BARGE_IN: 'USER_BARGE_IN',
  LISTENING_READY: 'LISTENING_READY',
  FAILURE: 'FAILURE',
  RESET: 'RESET'
};
